##===- lib/Makefile ---------------*- Makefile -*-===##

LEVEL=..

PARALLEL_DIRS=ExecutionTracer BinaryReaders Utils

#LIBRARYNAME=s2etools
#DONT_BUILD_RELINKED=1
#BUILD_ARCHIVE=1

include $(LEVEL)/Makefile.common

