/* Automatically generated by configure - do not modify */
#define CONFIG_QEMU_SHAREDIR "/usr/local/share/qemu"
#define HOST_I386 1
#define HOST_LONG_BITS 32
#define CONFIG_GDBSTUB 1
#define CONFIG_SLIRP 1
#define CONFIG_OSS 1
#define QEMU_VERSION "0.8.2"
#define O_LARGEFILE 0
#define MAP_ANONYMOUS MAP_ANON
#define CONFIG_BSD 1
#define CONFIG_UNAME_RELEASE ""
#define CONFIG_SKINS 1
