#===-- lib/Basic/Makefile ----------------------------------*- Makefile -*--===#
#
#
#===------------------------------------------------------------------------===#

LEVEL=../..

LIBRARYNAME=executiontracer
DONT_BUILD_RELINKED=1
BUILD_ARCHIVE=1

include $(LEVEL)/Makefile.common
