/* Automatically generated by configure - do not modify */
#define CONFIG_QEMU_SHAREDIR "/usr/local/share/qemu"
#define HOST_I386 1
#define HOST_LONG_BITS 32
#define CONFIG_DARWIN 1
#define CONFIG_GDBSTUB 1
#define CONFIG_SLIRP 1
#define QEMU_VERSION "0.10.50"
#define QEMU_PKGVERSION "Android"
#define O_LARGEFILE 0
#define MAP_ANONYMOUS MAP_ANON
#define HAVE_IOVEC 1
#define _BSD 1
#define CONFIG_SKINS 1
#define CONFIG_UNAME_RELEASE ""
