#===-- tools/klee/Makefile ---------------------------------*- Makefile -*--===#
#
#
#
#===------------------------------------------------------------------------===#

LEVEL=../..
TOOLNAME = icounter
USEDLIBS = executiontracer.a binaryreaders.a
LINK_COMPONENTS = support system

include $(LEVEL)/Makefile.common


LIBS += $(SIGCPP_LIB) $(TOOL_LIBS)
#-ltcmalloc
