#===-- tools/klee/Makefile ---------------------------------*- Makefile -*--===#
#
#                     The KLEE Symbolic Virtual Machine
#
# This file is distributed under the University of Illinois Open Source
# License. See LICENSE.TXT for details.
#
#===------------------------------------------------------------------------===#

LEVEL=../..
TOOLNAME = pfprofiler
USEDLIBS = executiontracer.a
LINK_COMPONENTS = 

include $(LEVEL)/Makefile.common


LIBS += 
#-ltcmalloc
