##===- tools/Makefile ---------------*- Makefile -*-===##
# 
# S2E
#
##===-----------------------------------------------===##

#
# Relative path to the top of the source tree.
#
LEVEL=..

#
# List all of the subdirectories that we will compile.
#
PARALLEL_DIRS=tbtrace coverage debugger s2etools-config forkprofiler icounter cacheprof
OPTIONAL_DIRS=static-translator

include $(LEVEL)/Makefile.common
