##===- s2etools/Makefile ------------------------*- Makefile -*-===##
#
# S2ETOOLS
#
##===-----------------------------------------------------------===##

#
# Indicates our relative path to the top of the project's root directory.
#
LEVEL = .
PARALLEL_DIRS = 
DIRS = lib tools
EXTRA_DIST = include

#
# Include the Master Makefile that knows how to build all.
#
include $(LEVEL)/Makefile.common


