#===-- tools/klee/Makefile ---------------------------------*- Makefile -*--===#
#
#
#
#===------------------------------------------------------------------------===#

LEVEL=../..
TOOLNAME = tbtrace
USEDLIBS = executiontracer.a binaryreaders.a utils.a
LINK_COMPONENTS = support

include $(LEVEL)/Makefile.common


LIBS += $(TOOL_LIBS)
#-ltcmalloc
