#===-- tools/klee/Makefile ---------------------------------*- Makefile -*--===#
#
#
#
#===------------------------------------------------------------------------===#

LEVEL=../..
TOOLNAME = debugger
USEDLIBS = executiontracer.a binaryreaders.a
LINK_COMPONENTS = support system

include $(LEVEL)/Makefile.common


LIBS += -lsigc-2.0 -lbfd -lintl -liberty -lz
#-ltcmalloc
